### ISSUE TITLE
PyPI release v0.0.13 is broken upon import

### ISSUE THREAD

**Issue by matthewfeickert** [andrzejnovak/mplhep#6]
@andrzejnovak The current release of mplhep on PyPI ([`v0.0.13`](https://pypi.org/project/mplhep/0.0.13/)) is broken upon import due to a missing module:

```
ModuleNotFoundError: No module named 'mplhep.error_estimation'
```

**Minimal failing example**

```
$ python --version
Python 3.7.5rc1
$ python -m venv test-example
$ source ~/test-example/bin/activate
(test-example) $ pip install --upgrade pip setuptools wheel
(test-example) $ pip list
Package       Version
------------- -------
pip           19.3.1 
pkg-resources 0.0.0  
setuptools    41.6.0 
wheel         0.33.6 
(test-example) $ pip install mplhep
(test-example) $ pip list | grep mplhep
mplhep          0.0.13
(test-example) $ python
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> import matplotlib.pyplot as plt
>>> import mplhep as hep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/.venvs/test-example/lib/python3.7/site-packages/mplhep/__init__.py", line 5, in <module>
    from . import cms
  File "/home/feickert/.venvs/test-example/lib/python3.7/site-packages/mplhep/cms.py", line 6, in <module>
    from . import plot
  File "/home/feickert/.venvs/test-example/lib/python3.7/site-packages/mplhep/plot.py", line 7, in <module>
    from .error_estimation import poisson_interval
ModuleNotFoundError: No module named 'mplhep.error_estimation'

```

**Comment by andrzejnovak** [comment]
Whoops, fixing this ASAP. I really need to add proper test suite. Thanks

**Comment by andrzejnovak** [comment]
@matthewfeickert v0.0.14 should be fine

**Comment by matthewfeickert** [comment]
> I really need to add proper test suite.

I'm willing to help on that front if you don't mind me making some opinionated PRs. :)

> `v0.0.14` should be fine

Yup. This now just needs to add `scipy` as a required install dependency, but then this works.

**Comment by andrzejnovak** [comment]
Hehe, PR's are welcome, even opinionated ones :)
